$courseName = "TempusStylus";
$courseVersion = "25.1";
$releaseDate = "May 2025";
$tempDir = "./.test";
$reportFile = "$tempDir/testReport";
$osName = "Linux";
%toolExeAndExpr = ('tempus' => '-version', 'innovus' => '-version');
%toolExeAndVersion = ('tempus' => 'v25.1', 'innovus' => 'v25.1');
%toolExeAndLogfile = ('tempus' => 'ANY', 'innovus' => 'ANY');
%toolExeAndSoftRel = ('tempus' => 'SSV251', 'innovus' => 'INNOVUS251');
%toolExeAndLicenses = ('tempus' => 'Tempus_Timing_Signoff_XL', 'innovus' => 'Innovus_Implementation_System');
%toolExeAndNumLicenses = ('tempus' => '2', 'innovus' => '1');
$additionalLogTestString = "";
$useCheckSysConf = "YES";
%toolExeAndCheckSoftRel = ('innovus' => 'INNOVUS251', 'tempus' => 'SSV251');
$osVersion = "ANY";
$cpuArch = "ANY";
$machType = "ANY";
$physMem = "ANY";
$totalSwap = "ANY";
$freeDisk = "ANY";
$additionalFile = "";
$comment = "This course is meant for Cadence classrooms only. For offsites, please contact the developer for library data.";
