##**************************************************
##*                                                
##* Copyright (C) 2011 Cadence Design Systems, Inc.
##* All rights reserved.
##*
##* CCD SCRIPT FILE: /home/shadab/shadab/tempus_labs_CUI/gtd/work/checkSdcDir/checkSdcCCD.do
##* GENERATED BY   : check_sdc_ccd 
##* INNOVUS        : 17.21-s086_1
##* TIME GENERATED : 02/02/2026 12:37:59
##*
##* NOTE: Requires Conformal Constraint Designer
##*       Release 08.10 or later
##*
##**************************************************

##***********************************************
## set up log file, get misc info about the run
##***********************************************
set_log_file /home/shadab/shadab/tempus_labs_CUI/gtd/work/checkSdcDir/checkSdcCCD.log -replace
set_dofile_abort off
set_undefined_cell Black_box
set_rule_handling -limit 1000 *

##***********************************************
## these values are default in latest CCD versions
## setting manually in case older CCD is used
##***********************************************
set_ccd_option -prove_set_reset_fp
set_ccd_option -prove_cdc_fp


##*****************************************************************
## turns *off* propagation of constants through sequential elements
## Note: ccd default: on, cte default: off
##*****************************************************************
set_flatten_model -nocase_analysis_sequential_propagation


##***********************************************
## read library in verilog or liberty format
##***********************************************
read_library -liberty   -unzip /home/shadab/shadab/tempus_labs_CUI/libs/liberty/pllclk_slow.lib.gz \
   /home/shadab/shadab/tempus_labs_CUI/libs/liberty/rom_via_metro_ss_1p08v_1p08v_125c_syn.lib.gz \
   /home/shadab/shadab/tempus_labs_CUI/libs/liberty/scmetro_cmos10lp_rvt_ss_1p08v_125c.lib.gz \
   /home/shadab/shadab/tempus_labs_CUI/libs/liberty/scmetropmk_cmos10lp_rvt_ss_0p9v_125c.lib.gz \
   /home/shadab/shadab/tempus_labs_CUI/libs/liberty/scmetropmk_cmos10lp_rvt_ss_0p9v_1p08v_125c.lib.gz \
   /home/shadab/shadab/tempus_labs_CUI/libs/liberty/scmetropmk_cmos10lp_rvt_ss_1p08v_0p9v_125c.lib.gz \
   /home/shadab/shadab/tempus_labs_CUI/libs/liberty/scmetropmk_cmos10lp_rvt_ss_1p08v_125c.lib.gz \
   /home/shadab/shadab/tempus_labs_CUI/libs/liberty/sram_sp_metro_ss_1p08v_1p08v_125c_syn.lib.gz \
  

##***********************************************
## read design
##***********************************************
read_design  /home/shadab/shadab/tempus_labs_CUI/gtd/work/checkSdcDir/dtmf_recvr_core.v   -replace 

##***********************************************
## Default enabled CCD rules
##***********************************************
set_ccd_parameter SDC_AUTO_CHECK_SEVERITY Error

##***********************************************
## User enabled CCD rules
##***********************************************
add_rule_set -file ccd_default_sdc_ruleset.ntcl > /dev/null


##***********************************************
## check if designs are clean + report design data
##***********************************************
report_design_data
report_black_box
## report module
report_floating_signals
usage

##***********************************************
## read SDCs
##***********************************************
set_system_mode setup
set_sdc_design / 
read_sdc /home/shadab/shadab/tempus_labs_CUI/gtd/work/../scripts/dtmf_recvr_core.sdc -replace

report_rule_check -sdc_lint * -status fail -verbose >  /home/shadab/shadab/tempus_labs_CUI/gtd/work/checkSdcDir/sdc_lint_checks.rpt
##***********************************************
## read user do files
##***********************************************

set_system_mode verify
usage

##***********************************************
## delete the default clock group as SDC has no set_clock_group.
##***********************************************
delete_clock_group -all
add_clock_group -single
commit_clock
report_clock_group

##***********************************************
## check SDC Constraints:
##***********************************************
run_rule_check sdc_def_checks
report_rule_check sdc_def_checks -status fail -verbose -limit 100 > /home/shadab/shadab/tempus_labs_CUI/gtd/work/checkSdcDir/rule_check.quality.rpt
echo "==============================================================================="
echo "=            Rule Check Summary    "
echo "==============================================================================="
report_rule_check sdc_def_checks

usage

echo " Info: Generated SDC rule check report:"
echo "       /home/shadab/shadab/tempus_labs_CUI/gtd/work/checkSdcDir/rule_check.quality.rpt"

usage

##***********************************************
## start GUI
##***********************************************
## set_gui on

##***********************************************
## exit CCD
##***********************************************
exit
